### PR TITLE
Check for valid types in themes.

### PR DESCRIPTION
**Pull request by landabaso**
Fixes https://github.com/javivelasco/react-css-themr/issues/44

### CODE REVIEW

**Comment by javivelasco** [comment]
Thank you!

**Comment by hardchor** [comment]
@javivelasco Any chance you could merge this into 1.7.2 and do a quick release until https://github.com/react-toolbox/react-toolbox upgrades their version (see https://github.com/react-toolbox/react-toolbox/issues/1335)?

**Comment by javivelasco** [comment]
Don't worry, gonna release a new react toolbox version including react-css-themr changes

**Comment by burkhardr** [comment]
Wasn't worried ;) I know you're doing great work on this and it's hugely appreciated!

**Pull request merged**
